---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

We are going to make some plotly plots. 

```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

Let's get some data

```{r}
data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  select(
    borough = neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    !is.na(rating), 
    borough == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```

Let's make a scatterplot!!

```{r}
nyc_airbnb %>%
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) %>% 
  # ‘\n means land break between two text labels
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)

# plot_ly and gg_plot are similar, but they have difference in ()
#text-label 让图形里每个点都可以拥有text解释，when 鼠标移动到那个点的时候
```


```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
```

We can also make barchar 

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```

```{r}
scatter_ggplot = 
  nyc_airbnb %>%
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point(alpha = 0.25) +
  coord_cartesian()

ggplotly(scatter_ggplot)
```

